build:
  tests:
    override:
      - command: vendor/bin/phpunit
        coverage:
          file: /tmp/coverage.xml
          format: clover

  nodes:
    tests-php72:
      environment:
        php: 7.2

    tests-php73:
      environment:
        php: 7.3

    tests-php74:
      environment:
        php: 7.4

    analysis:
      tests:
        override:
          - php-scrutinizer-run